apiVersion: v1
kind: PersistentVolume      #pv just cretaed its only ebs 
metadata:
  name: ebs-static          #pvc is if pv wnats to interact or attach to pod/node then pvc need
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0098e8b28652cd81a
---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  