apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: "efs-pv"
  resources:
    requests:
      storage: 5Gi