apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: "efs-pv"
  resources:
    requests:
      storage: 5Gi
  
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels: 
    purpose: "efs-static-demo"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-pv
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-static-demo"  
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31150
