kind: Pod
apiVersion: v1
metadata:
  name: resources
spec: 
  containers:
  - name: nginx
    image: nginx
    resources: 
      resources:
        limits:
          cpu: "500m"         # 500 millicores (0.5 vCPU)
          memory: "512Mi"     # 512 MiB RAM
        requests:
          cpu: "250m"         # 0.25 vCPU
          memory: "256Mi"     # 256 MiB RAM
