kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
      project : expense
      component: backend
      environment: dev
      version: "1.0.0"
      demo: np
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31152

---
# using LB load will distribute across nodes we can access from internet
kind: Pod
apiVersion: v1
metadata: 
  name: backend-lb
  labels: 
      project : expense
      component: backend
      environment: dev
      version: "1.0.0"
      demo: np
spec:
  containers:
    - name: nginx
      image: nginx
